import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignUp,
  // SignInButton,
  // SignUpButton,
  UserButton
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
              <Show when="signed-out" >
                <section className= "flex min-h-screen w-screen items-center justify-center">
                  <SignUp />
                </section>
              </Show>
            <Show when="signed-in">
              <div className="flex min-h-screen flex-col bg-slate-100">
                <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/90 backdrop-blur">
                  <div className="mx-auto flex h-16 w-full max-w-[1600px] items-center justify-between px-4 md:px-6">
                    <div className="flex items-center gap-3">
                      <span className="text-2xl leading-none" aria-hidden="true">🤖</span>
                      <p className="text-sm font-semibold tracking-wide text-slate-700">RAG PDF Assistant</p>
                    </div>
                    <div className="rounded-full border border-slate-200 bg-white p-1 shadow-sm">
                      <UserButton
                        appearance={{
                          elements: {
                            avatarBox: "h-8 w-8",
                          },
                        }}
                      />
                    </div>
                  </div>
                </header>
                <main className="flex-1">{children}</main>
              </div>
            </Show>
        </ClerkProvider>
      </body>
    </html>
  );
}
